#
# This is free software, lisence use MIT.
#
# Copyright (C) 2019 P3TERX <https://p3terx.com>
# Copyright (C) 2020 KFERMercer <KFER.Mercer@gmail.com>
#
# <https://github.com/KFERMercer/OpenWrt-CI>
#

name: LEDE-CI-IPQ60xx

on:
  push:
    branches:
      - master
  # schedule:
  #   - cron: 0 20 * * *
  release:
    types: [published]

jobs:
  build_openwrt:
    name: Build LEDE IPQ60xx Firmware

    runs-on: ubuntu-22.04

    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: 硬件信息
        run: |
          echo "=======================当前CPU信息======================="
          cat /proc/cpuinfo
          echo "=======================当前内存信息======================="
          cat /proc/meminfo
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: coolsnowwolf/lede
          ref: master
      - name: List Repo Files
        run: |
          echo "=======================源文件列表：======================="
          ls -lth
          # sed -i 's/KERNEL_PATCHVER:=6.6/KERNEL_PATCHVER:=6.12/g' ./target/linux/qualcommax/Makefile
          echo "=======================内核版本结果如下：======================="
          cat -n ./target/linux/qualcommax/Makefile
          echo "=======================当前软件包占用排行榜：======================="
          sudo dpkg-query -W --showformat='${Installed-Size} ${Package} ${Status}\n'|grep -v deinstall|sort -n -r|awk '{print $1" "$2}' | head -n 40
      # - name: 包清理
      #   env:
      #     DEBIAN_FRONTEND: noninteractive
      #   run: |
      #     echo "=======================当前磁盘占用======================="
      #     df -lTh
      #     echo "=======================docker镜像占用======================="
      #     docker images
      #     echo "=======================docker容器占用======================="
      #     docker ps -a
      #     docker rmi `docker images -q`
      #     echo "=======================docker容器占用======================="
      #     sudo apt-get -y update
      #     sudo apt-get -y remove android* azure* microsoft* dotnet* temurin-*-jdk google* llvm* firefox* powershell mysql* mono* libllvm* snapd* moby* libclang* moby* mecab*
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: true
          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          swap-storage: true
      - name: 文件清理
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          echo "=======================清理前当前磁盘占用======================="
          df -lTh
          echo "=======================开始统计文件夹占用======================="
          sudo du --max-depth=4 --exclude=\/mnt / | grep "^[0-9]\{5,\}" | sort -k 1 -r -n
          echo "=======================开始清理文件夹======================="
          sudo -E rm -rf /usr/local/lib/android
          sudo -E rm -rf /opt/hostedtoolcache
          sudo -E rm -rf /usr/local/share/powershell
          sudo -E rm -rf /usr/local/lib/node_modules
          sudo -E rm -rf /home/linuxbrew
          echo "=======================清理后当前磁盘占用======================="
          df -lTh
      - name: 安装依赖包
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          echo "=======================开始安装依赖包======================="
          sudo -E apt-get update -y
          sudo -E apt-get full-upgrade -y
          sudo -E apt-get install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential \
            bzip2 ccache clang cmake cpio curl device-tree-compiler flex gawk gcc-multilib g++-multilib gettext \
            genisoimage git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libfuse-dev libglib2.0-dev \
            libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libpython3-dev \
            libreadline-dev libssl-dev libtool llvm lrzsz libnsl-dev ninja-build p7zip p7zip-full patch pkgconf \
            python3 python3-pyelftools python3-setuptools qemu-utils rsync scons squashfs-tools subversion \
            swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev
          echo "=======================当前磁盘占用======================="
          df -lTh
      - name: Apply Patch
        run: |
          rm -f ./target/linux/qualcommax/patches-6.12/0600-1-qca-nss-ecm-support-CORE.patch && \
          curl -o ./target/linux/qualcommax/patches-6.12/0600-1-qca-nss-ecm-support-CORE.patch \
            https://raw.githubusercontent.com/zzasa/OpenWrt-CI/master/.github/workflows/patch/0600-1-qca-nss-ecm-support-CORE.patch
          echo "应用qca-nss-ecm-support-CORE补丁结果如下："
          cat -n ./target/linux/qualcommax/patches-6.12/0600-1-qca-nss-ecm-support-CORE.patch
      - name: Update feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Download configuration file
        run: |
          rm -f ./.config*
          curl -o ./.config https://raw.githubusercontent.com/zzasa/OpenWrt-CI/master/.github/workflows/ipq60xx.config

      - name: Show custom configuration
        run: |
          cat -n ./.config

      - name: Generate final configuration
        run: |
          make defconfig
          cat -n ./.config

      - name: Make download
        run: |
          make download -j8 || make download -j1 V=s
          rm -rf $(find ./dl/ -size -1024c)
      - name: Apply Kernel Patch
        run: |
          tree ./build_dir
          sed -i 's/CACHELINE_ASSERT_GROUP_SIZE(struct net_device, net_device_read_tx, 160);/CACHELINE_ASSERT_GROUP_SIZE(struct net_device, net_device_read_tx, 192);/g' \
            ./build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq60xx/linux-6.12.68/net/core/dev.c

      - name: Disk Usage
        run: |
          echo "=======================当前磁盘占用======================="
          df -lTh

      - name: Compile firmware
        run: |
          make -j$(nproc) || make -j1 V=s

      - name: Disk Usage
        run: |
          echo "======================="
          echo "=======================当前磁盘占用======================="
          df -lTh
          echo "======================="
          du -h ./ --max-depth=3

      - name: Prepare artifact
        run: |
          echo "=======================编译后的目标文件列表如下：======================="
          tree ./bin/targets/
          echo "=======================开始压缩固件======================================="
          tar Jcvf firmware.tar.xz ./bin/targets/
          echo "=======================压缩固件结果======================================="
          ls -lth firmware.tar.xz

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: LEDE_firmware
          path: ./firmware.tar.xz
