#
# This is free software, lisence use MIT.
#
# Copyright (C) 2019 P3TERX <https://p3terx.com>
# Copyright (C) 2020 KFERMercer <KFER.Mercer@gmail.com>
#
# <https://github.com/KFERMercer/OpenWrt-CI>
#

name: LEDE-CI-x86_64

on:
  push:
    branches:
      - master
  # schedule:
  #   - cron: 0 20 * * *
  release:
    types: [published]

jobs:
  build_openwrt:
    name: Build LEDE firmware

    runs-on: ubuntu-latest

    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: coolsnowwolf/lede
          ref: master

      - name: List Repo Files
        run: |
          echo "=======================源文件列表：======================="
          ls -lth
          # sed -i 's/KERNEL_PATCHVER:=5.10/KERNEL_PATCHVER:=5.15/g' ./target/linux/x86/Makefile
          echo "=======================内核版本结果如下：======================="
          cat -n ./target/linux/x86/Makefile
          echo "=======================当前软件包占用排行榜：======================="
          sudo dpkg-query -W --showformat='${Installed-Size} ${Package} ${Status}\n'|grep -v deinstall|sort -n -r|awk '{print $1" "$2}' | head -n 40
      - name: 空间清理
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          echo "=======================当前磁盘占用======================="
          df -lTh
          echo "=======================docker镜像占用======================="
          docker images
          echo "=======================docker容器占用======================="
          docker ps -a
          docker rmi `docker images -q`
          echo "=======================docker容器占用======================="
          sudo apt-get -y remove azure* microsoft* dotnet* temurin-*-jdk google* llvm* firefox* powershell mysql* mono* libllvm* snapd* moby* libclang* moby* mecab*
      - name: 安装依赖包
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          echo "=======================统计文件夹占用======================="
          sudo du --max-depth=4 --exclude=\/mnt / | grep "^[0-9]\{5,\}" | sort -k 1 -r -n
          echo "=======================统计文件夹占用======================="
          sudo -E apt-get -y upgrade
          sudo -E sudo apt-get install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential \
            bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib \
            git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev \
            libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libreadline-dev libssl-dev libtool lrzsz \
            mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pip libpython3-dev qemu-utils \
            rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev
      - name: Disk Usage
        run: |
          echo "=======================当前磁盘占用======================="
          df -lTh

      - name: Update feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Download configuration file
        run: |
          rm -f ./.config*
          curl -o ./.config https://raw.githubusercontent.com/zzasa/OpenWrt-CI/master/.github/workflows/lede-config

      - name: Show custom configuration
        run: |
          cat -n ./.config

      - name: Generate final configuration
        run: |
          make defconfig
          cat -n ./.config

      - name: Make download
        run: |
          make download -j8 || make download -j1 V=s
          rm -rf $(find ./dl/ -size -1024c)

      - name: Disk Usage
        run: |
          echo "=======================当前磁盘占用======================="
          df -lTh

      - name: Compile firmware
        run: |
          make -j$(nproc) || make -j1 V=s

      - name: Disk Usage
        run: |
          echo "======================="
          echo "=======================当前磁盘占用======================="
          df -lTh
          echo "======================="
          du -h ./ --max-depth=1
          du -h /mnt/openwrt/ --max-depth=1 || true

      - name: Prepare artifact
        run: |
          echo "=======================编译后的目标文件列表如下：======================="
          tree ./bin/targets/
          echo "=======================开始压缩固件======================================="
          tar Jcvf firmware.tar.xz ./bin/targets/
          echo "=======================压缩固件结果======================================="
          ls -lth firmware.tar.xz

      - name: Deliver firmware
        uses: actions/upload-artifact@v2
        with:
          name: LEDE_firmware
          path: ./firmware.tar.xz

      - name: Upload release asset
        if: github.event == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.YOURTOKEN }}
          file: ./artifact/firmware/*
          tag: ${{ github.ref }}
          file_glob: true
