#
# This is free software, lisence use MIT.
# 
# Copyright (C) 2019 P3TERX <https://p3terx.com>
# Copyright (C) 2020 KFERMercer <KFER.Mercer@gmail.com>
# 
# <https://github.com/KFERMercer/OpenWrt-CI>
#

name: OpenWrt-CI

on:
  push:
    branches: 
      - master1
  # schedule:
  #   - cron: 0 20 * * *
  release:
    types: [published]

jobs:

  build_openwrt:

    name: Build OpenWrt firmware

    runs-on: ubuntu-latest

    if: github.event.repository.owner.id == github.event.sender.id

    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: openwrt/openwrt
          ref: master

      - name: List Repo Files
        run: |
          ls -lth

      - name: Space cleanup
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php* android*
          sudo -E apt-get update
          sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler antlr3 gperf swig libtinfo5 tree
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean

          # sudo mkdir -p -m 777 /mnt/openwrt/bin /mnt/openwrt/build_dir/host /mnt/openwrt/build_dir/hostpkg /mnt/openwrt/dl /mnt/openwrt/feeds /mnt/openwrt/staging_dir
          # ln -s /mnt/openwrt/bin ./bin
          # mkdir -p ./build_dir
          # ln -s -f /mnt/openwrt/build_dir/host ./build_dir/host
          # ln -s -f /mnt/openwrt/build_dir/hostpkg ./build_dir/hostpkg
          # ln -s /mnt/openwrt/dl ./dl
          # ln -s /mnt/openwrt/feeds ./feeds
          # ln -s /mnt/openwrt/staging_dir ./staging_dir

          df -h

      - name: Update feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Generate configuration file
        run: |
          rm -f ./.config*
          touch ./.config

          #
          # 在 cat >> .config <<EOF 到 EOF 之间粘贴你的编译配置, 需注意缩进关系
          # 例如:

          cat >> .config <<EOF
            CONFIG_KERNEL_BUILD_USER="OpenWrt-CI"
            CONFIG_KERNEL_BUILD_DOMAIN="Azure"
            CONFIG_TARGET_x86=y
            CONFIG_TARGET_x86_64=y
            CONFIG_TARGET_x86_64_DEVICE_generic=y
            CONFIG_TARGET_PROFILE="DEVICE_generic"
            CONFIG_TARGET_ARCH_PACKAGES="x86_64"

          # Target Images
            # CONFIG_TARGET_ROOTFS_INITRAMFS is not set
            CONFIG_EXTERNAL_CPIO=""

          # Image Options
            CONFIG_TARGET_IMAGES_GZIP=y
            # CONFIG_ISO_IMAGES is not set
            # CONFIG_VDI_IMAGES is not set
            # CONFIG_VMDK_IMAGES is not set
            # CONFIG_GRUB_IMAGES is not set
            # CONFIG_TARGET_ROOTFS_EXT4FS is not set
            CONFIG_GRUB_EFI_IMAGES=y
            CONFIG_TARGET_ROOTFS_SQUASHFS=y
            CONFIG_TARGET_SQUASHFS_BLOCK_SIZE=256
            CONFIG_TARGET_UBIFS_FREE_SPACE_FIXUP=y
            CONFIG_TARGET_UBIFS_JOURNAL_SIZE=""
            CONFIG_TARGET_KERNEL_PARTSIZE=16
            CONFIG_TARGET_ROOTFS_PARTSIZE=256
            CONFIG_TARGET_ROOTFS_PARTNAME=""
            CONFIG_TARGET_ROOTFS_PERSIST_VAR=y

          # Firmware
            CONFIG_PACKAGE_iwlwifi-firmware-iwl6000g2=y
            CONFIG_PACKAGE_iwlwifi-firmware-iwl6000g2a=y
            CONFIG_PACKAGE_iwlwifi-firmware-iwl6000g2b=y
            CONFIG_PACKAGE_iwlwifi-firmware-iwl7265=y
            CONFIG_PACKAGE_iwlwifi-firmware-iwl7265d=y
            CONFIG_PACKAGE_rtl8822ce-firmware=y

          # Block Devices
            CONFIG_PACKAGE_kmod-ata-ahci=y
            CONFIG_PACKAGE_kmod-loop=y
            CONFIG_PACKAGE_kmod-scsi-cdrom=y
          
          # Filesystems
            CONFIG_PACKAGE_kmod-fs-btrfs=y
            CONFIG_PACKAGE_kmod-fs-exfat=y
            CONFIG_PACKAGE_kmod-fs-ext4=y
            CONFIG_PACKAGE_kmod-fs-f2fs=y
            CONFIG_PACKAGE_kmod-fs-isofs=y
            CONFIG_PACKAGE_kmod-fs-hfsplus=y
            CONFIG_PACKAGE_kmod-fs-msdos=y
            CONFIG_PACKAGE_kmod-fs-ntfs=y
            CONFIG_PACKAGE_kmod-fs-squashfs=y
            CONFIG_PACKAGE_kmod-fs-udf=y
            CONFIG_PACKAGE_kmod-fs-vfat=y
            CONFIG_PACKAGE_kmod-fs-ksmbd=y
            CONFIG_KSMBD_SMB_INSECURE_SERVER=y
            CONFIG_PACKAGE_kmod-fs-nfs=y
            CONFIG_PACKAGE_kmod-fs-nfs-common=y
            CONFIG_PACKAGE_kmod-fs-nfs-common-rpcsec=y
            CONFIG_PACKAGE_kmod-fs-nfsd=y
            CONFIG_PACKAGE_kmod-fs-xfs=y

          # Native Language Support
            CONFIG_PACKAGE_kmod-nls-cp936=y
            CONFIG_PACKAGE_kmod-nls-cp950=y

          # Network Devices
            CONFIG_PACKAGE_kmod-e1000=y
            CONFIG_PACKAGE_kmod-e1000e=y
            CONFIG_PACKAGE_kmod-vmxnet3=y
            CONFIG_TARGET_PREINIT_IP="192.168.1.2"
            CONFIG_TARGET_PREINIT_NETMASK="255.255.255.0"
            CONFIG_TARGET_PREINIT_BROADCAST="192.168.1.255"

          # USB Support
            CONFIG_PACKAGE_kmod-usb-net-rtl8150=y
            CONFIG_PACKAGE_kmod-usb-net-rtl8152=y
            CONFIG_PACKAGE_kmod-usb-storage=y
            CONFIG_PACKAGE_kmod-usb-storage-extras=y
            CONFIG_PACKAGE_kmod-usb-storage-uas=y
            CONFIG_PACKAGE_kmod-usb-xhci-hcd=y
            CONFIG_PACKAGE_kmod-usb2=y
            CONFIG_PACKAGE_kmod-usb3=y

          # Virtualization
            CONFIG_PACKAGE_kmod-kvm-intel=y
            CONFIG_PACKAGE_kmod-kvm-x86=y

          # Wireless Drivers
            CONFIG_PACKAGE_kmod-iwlwifi=y
            CONFIG_PACKAGE_kmod-rtw88=y
          
          # Base system
            CONFIG_PACKAGE_block-mount=y

          # Disc
            CONFIG_PACKAGE_blkid=y
            CONFIG_PACKAGE_cfdisk=y
            CONFIG_PACKAGE_fdisk=y
            CONFIG_PACKAGE_lsblk=y

          # LuCI
            CONFIG_PACKAGE_luci=y
            CONFIG_PACKAGE_luci-lib-docker=y
            CONFIG_PACKAGE_luci-base=y
            CONFIG_LUCI_JSMIN=y
            CONFIG_LUCI_CSSTIDY=y
            CONFIG_LUCI_LANG_zh_Hans=y
            CONFIG_PACKAGE_luci-compat=y
            CONFIG_PACKAGE_luci-mod-admin-full=y
            CONFIG_PACKAGE_luci-mod-network=y
            CONFIG_PACKAGE_luci-mod-status=y
            CONFIG_PACKAGE_luci-mod-system=y

          # Applications
            CONFIG_PACKAGE_luci-app-acl=y
            # CONFIG_PACKAGE_luci-app-acme is not set
            CONFIG_PACKAGE_luci-app-adblock=y
            CONFIG_PACKAGE_luci-app-advanced-reboot=y
            # CONFIG_PACKAGE_luci-app-ahcp is not set
            CONFIG_PACKAGE_luci-app-aria2=y
            CONFIG_PACKAGE_luci-app-attendedsysupgrade=y
            # CONFIG_PACKAGE_luci-app-babeld is not set
            # CONFIG_PACKAGE_luci-app-banip is not set
            # CONFIG_PACKAGE_luci-app-bcp38 is not set
            # CONFIG_PACKAGE_luci-app-bird1-ipv4 is not set
            # CONFIG_PACKAGE_luci-app-bird1-ipv6 is not set
            # CONFIG_PACKAGE_luci-app-bmx6 is not set
            # CONFIG_PACKAGE_luci-app-bmx7 is not set
            # CONFIG_PACKAGE_luci-app-cjdns is not set
            # CONFIG_PACKAGE_luci-app-clamav is not set
            CONFIG_PACKAGE_luci-app-commands=y
            # CONFIG_PACKAGE_luci-app-cshark is not set
            # CONFIG_PACKAGE_luci-app-dawn is not set
            # CONFIG_PACKAGE_luci-app-dcwapd is not set
            CONFIG_PACKAGE_luci-app-ddns=y
            CONFIG_PACKAGE_luci-app-diag-core=y
            CONFIG_PACKAGE_luci-app-dnscrypt-proxy=y
            CONFIG_PACKAGE_luci-app-dockerman=y
            # CONFIG_PACKAGE_luci-app-dump1090 is not set
            # CONFIG_PACKAGE_luci-app-dynapoint is not set
            # CONFIG_PACKAGE_luci-app-eoip is not set
            # CONFIG_PACKAGE_luci-app-example is not set
            CONFIG_PACKAGE_luci-app-firewall=y
            # CONFIG_PACKAGE_luci-app-frpc is not set
            # CONFIG_PACKAGE_luci-app-frps is not set
            # CONFIG_PACKAGE_luci-app-fwknopd is not set
            # CONFIG_PACKAGE_luci-app-hd-idle is not set
            # CONFIG_PACKAGE_luci-app-hnet is not set
            CONFIG_PACKAGE_luci-app-https-dns-proxy=y
            # CONFIG_PACKAGE_luci-app-ksmbd is not set
            # CONFIG_PACKAGE_luci-app-ledtrig-rssi is not set
            # CONFIG_PACKAGE_luci-app-ledtrig-switch is not set
            # CONFIG_PACKAGE_luci-app-ledtrig-usbport is not set
            # CONFIG_PACKAGE_luci-app-lxc is not set
            # CONFIG_PACKAGE_luci-app-minidlna is not set
            # CONFIG_PACKAGE_luci-app-mjpg-streamer is not set
            # CONFIG_PACKAGE_luci-app-mwan3 is not set
            # CONFIG_PACKAGE_luci-app-nextdns is not set
            CONFIG_PACKAGE_luci-app-nft-qos=y
            # CONFIG_PACKAGE_luci-app-nlbwmon is not set
            # CONFIG_PACKAGE_luci-app-ntpc is not set
            # CONFIG_PACKAGE_luci-app-nut is not set
            # CONFIG_PACKAGE_luci-app-ocserv is not set
            # CONFIG_PACKAGE_luci-app-olsr is not set
            # CONFIG_PACKAGE_luci-app-olsr-services is not set
            # CONFIG_PACKAGE_luci-app-olsr-viz is not set
            # CONFIG_PACKAGE_luci-app-omcproxy is not set
            # CONFIG_PACKAGE_luci-app-openvpn is not set
            CONFIG_PACKAGE_luci-app-opkg=y
            # CONFIG_PACKAGE_luci-app-p910nd is not set
            # CONFIG_PACKAGE_luci-app-pagekitec is not set
            # CONFIG_PACKAGE_luci-app-polipo is not set
            # CONFIG_PACKAGE_luci-app-privoxy is not set
            CONFIG_PACKAGE_luci-app-qos=y
            # CONFIG_PACKAGE_luci-app-radicale is not set
            # CONFIG_PACKAGE_luci-app-radicale2 is not set
            # CONFIG_PACKAGE_luci-app-rp-pppoe-server is not set
            CONFIG_PACKAGE_luci-app-samba4=y
            # CONFIG_PACKAGE_luci-app-ser2net is not set
            # CONFIG_PACKAGE_luci-app-shadowsocks-libev is not set
            # CONFIG_PACKAGE_luci-app-shairplay is not set
            # CONFIG_PACKAGE_luci-app-siitwizard is not set
            CONFIG_PACKAGE_luci-app-simple-adblock=y
            # CONFIG_PACKAGE_luci-app-smartdns is not set
            # CONFIG_PACKAGE_luci-app-snmpd is not set
            # CONFIG_PACKAGE_luci-app-softether is not set
            # CONFIG_PACKAGE_luci-app-splash is not set
            CONFIG_PACKAGE_luci-app-sqm=y
            # CONFIG_PACKAGE_luci-app-squid is not set
            CONFIG_PACKAGE_luci-app-statistics=y
            # CONFIG_PACKAGE_luci-app-tinyproxy is not set
            CONFIG_PACKAGE_luci-app-transmission=y
            # CONFIG_PACKAGE_luci-app-travelmate is not set
            # CONFIG_PACKAGE_luci-app-ttyd is not set
            # CONFIG_PACKAGE_luci-app-udpxy is not set
            # CONFIG_PACKAGE_luci-app-uhttpd is not set
            # CONFIG_PACKAGE_luci-app-unbound is not set
            CONFIG_PACKAGE_luci-app-upnp=y
            # CONFIG_PACKAGE_luci-app-vnstat is not set
            # CONFIG_PACKAGE_luci-app-vnstat2 is not set
            # CONFIG_PACKAGE_luci-app-vpn-policy-routing is not set
            # CONFIG_PACKAGE_luci-app-vpnbypass is not set
            CONFIG_PACKAGE_luci-app-watchcat=y
            # CONFIG_PACKAGE_luci-app-wifischedule is not set
            # CONFIG_PACKAGE_luci-app-wireguard is not set
            # CONFIG_PACKAGE_luci-app-wol is not set
            CONFIG_PACKAGE_luci-app-xinetd=y
            # CONFIG_PACKAGE_luci-app-yggdrasil is not set

          # Themes
            CONFIG_PACKAGE_luci-theme-bootstrap=y
            CONFIG_PACKAGE_luci-theme-material=y
            CONFIG_PACKAGE_luci-theme-openwrt=y
            CONFIG_PACKAGE_luci-theme-openwrt-2020=y

          # Protocols
            CONFIG_PACKAGE_luci-proto-ipv6=y
            CONFIG_PACKAGE_luci-proto-ppp=y
          EOF

          #
          # ===============================================================
          # 
          sed -i 's/^[ \t]*//g' ./.config

      - name: Show custom configuration
        run: |
          cat -n ./.config

      - name: Generate final configuration
        run: |
          make defconfig

      - name: Make download
        run: |
          make download -j8 || make download -j1 V=s
          rm -rf $(find ./dl/ -size -1024c)
          df -h

      - name: Compile firmware
        run: |
          make -j$(nproc) || make -j1 V=s
          echo "======================="
          echo "Space usage:"
          echo "======================="
          df -h
          echo "======================="
          du -h ./ --max-depth=1
          du -h /mnt/openwrt/ --max-depth=1 || true

      - name: Prepare artifact
        run: |
          echo "=======================编译后的目标文件列表如下：======================="
          tree ./bin/targets/
          echo "=======================显示完成======================================="
          mkdir -p ./artifact/firmware
          mkdir -p ./artifact/package
          mkdir -p ./artifact/buildinfo
          rm -rf $(find ./bin/targets/ -type d -name "packages")
          cp -rf $(find ./bin/targets/ -type f) ./artifact/firmware/
          find ./bin/targets/ -name "*sysupgrade*bin*" | xargs -i mv -f {} ./artifact/firmware/
          cp -rf $(find ./bin/packages/ -type f -name "*.ipk") ./artifact/package/
          cp -rf $(find ./bin/targets/ -type f -name "*.buildinfo" -o -name "*.manifest") ./artifact/buildinfo/

      - name: Deliver buildinfo
        uses: actions/upload-artifact@v2
        with:
          name: OpenWrt_buildinfo
          path: ./artifact/buildinfo/

      - name: Deliver package
        uses: actions/upload-artifact@v2
        with:
          name: OpenWrt_package
          path: ./artifact/package/

      - name: Deliver firmware
        uses: actions/upload-artifact@v2
        with:
          name: OpenWrt_firmware
          path: ./bin/targets/

      - name: Upload release asset
        if: github.event == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.YOURTOKEN }}
          file: ./artifact/firmware/*
          tag: ${{ github.ref }}
          file_glob: true
